export const EMAIL_CONFIG = {
  HELLO_MAIL: 'hello@frac.io',
  MAIL_REPLY_TO: 'support.frac@gmail.com',
  FROM_EMAIL: 'Frac Platform',
  DEFAUT_RECIVER: 'frac.announcement@gmail.com',
  SOCIAL_LINK: {
    TWITTER: 'https://x.com/diamondlabs_io',
    YOUTUBE: 'https://www.youtube.com/channel/UCcFnaT1QfJyqYBvJAw2pYEw',
    LINKEDIN: 'https://www.linkedin.com/company/diamondlabs-io',
  },
  CONTACT_US: {
    TRADER: `${process.env.TRADER_DOMAIN}/contact-us`,
    FRACTOR: `${process.env.FRACTOR_DOMAIN}/contact-us`,
  },
  DIR: {
    WHITELIST_ANNOUNCEMENT: 'whitelist-announcement',
    PARTICIPATION_TIME_START: 'participation-time-start',
    IAO_EVENT_FAILED: 'iao-event-failed',
    REJECT_IAO_REVENUE_TO_WHITELIST: 'reject-iao-revenue-to-whitelist',
    IAO_VAULT_SUCCESS: 'iao-vault-success',
    IAO_NON_VAULT_SUCCESS: 'iao-non-vault-success',
    ANNOUNCEMENTS: 'announcements',
    AFFILIATE_OFFERS: 'affiliate-offers',
    REQUEST_NFT_WITHDRAW: 'request-nft-withdraw',
    REDEMPTION_REQUEST_APPROVED: 'redemption-request-approved',
    REDEMPTION_REQUEST_REJECTED: 'redemption-request-rejected',
    WITHDRAWAL_REQUEST: 'withdrawal-request',
    CANCEL_WITHDRAWAL_REQUEST: 'cancel-request',
    SECOND_APPROVED_IAO_REQUEST: {
      EN: './admin-approved-iao-request-en.hbs',
      CN: './admin-approved-iao-request-cn.hbs',
      JA: './admin-approved-iao-request-ja.hbs',
      VI: './admin-approved-iao-request-vi.hbs',
    },
    REJECT_IAO_REQUEST: {
      EN: './reject-iao-request-en.hbs',
      CN: './reject-iao-request-cn.hbs',
      JA: './reject-iao-request-ja.hbs',
      VI: './reject-iao-request-vi.hbs',
    },
    CREATE_IAO_EVENT_PUBLIC: {
      EN: './create-iao-event-published-en.hbs',
      CN: './create-iao-event-published-cn.hbs',
      JA: './create-iao-event-published-ja.hbs',
      VI: './create-iao-event-published-vi.hbs',
    },
    VAULT_IAO_HAS_COMPLETED: {
      EN: './vault-iao-has-completed-en.hbs',
      CN: './vault-iao-has-completed-cn.hbs',
      JA: './vault-iao-has-completed-ja.hbs',
      VI: './vault-iao-has-completed-vi.hbs',
    },
    NON_VAULT_IAO_HAS_COMPLETED: {
      EN: './non-vault-has-completed-en.hbs',
      CN: './non-vault-has-completed-cn.hbs',
      JA: './non-vault-has-completed-ja.hbs',
      VI: './non-vault-has-completed-vi.hbs',
    },
    VAULT_IAO_HAS_FAILED: {
      EN: './vault-iao-has-failed-en.hbs',
      CN: './vault-iao-has-failed-cn.hbs',
      JA: './vault-iao-has-failed-ja.hbs',
      VI: './vault-iao-has-failed-vi.hbs',
    },
    APPROVED_IAO_REVENUE: {
      EN: './iao-result-has-been-approved-en.hbs',
      CN: './iao-result-has-been-approved-cn.hbs',
      JA: './iao-result-has-been-approved-ja.hbs',
      VI: './iao-result-has-been-approved-vi.hbs',
    },
    REJECT_IAO_REVENUE: {
      EN: './iao-result-has-been-rejected-en.hbs',
      CN: './iao-result-has-been-rejected-cn.hbs',
      JA: './iao-result-has-been-rejected-ja.hbs',
      VI: './iao-result-has-been-rejected-vi.hbs',
    },
    IAO_EVENT_VAULT_COMPLETED: 'iao-event-vault-completed',
    IAO_EVENT_VAULT_FAILED: 'iao-event-vault-failed',
    IAO_EVENT_NON_VAULT_COMPLETED: 'iao-event-non-vault-completed',
    FNFT_MERGED: 'fnft-merged',
    WHITELIST_EMPTY: 'whitelist-empty',
    DEACTIVATE_FRACTOR: 'deactivate-fractor',
    REACTIVATE_FRACTOR: 'reactivate-fractor',
    GAS_WALLET: 'gas-wallet',
    DEACTIVATE_TRADER: {
      EN: './deactivate-affiliate-en.hbs',
      CN: './deactivate-affiliate-cn.hbs',
      JA: './deactivate-affiliate-ja.hbs',
      VI: './deactivate-affiliate-vi.hbs',
    },
    REACTIVATE_TRADER: {
      EN: './active-affiliate-en.hbs',
      CN: './active-affiliate-cn.hbs',
      JA: './active-affiliate-ja.hbs',
      VI: './active-affiliate-vi.hbs',
    },
    SUBSCRIBER: 'subscriber',
  },
  TITLE: {
    DEACTIVATE_TRADER: {
      EN: '[Frac] Your Trader account has been deactivated',
      CN: '[Frac] 您的Trader账户已被停用',
      JP: '【Frac】アカウント凍結のお知らせ',
      VN: '[Frac] Tài khoản Trader của bạn đã bị vô hiệu hóa',
    },
    REACTIVATE_TRADER: {
      EN: '[Frac] Your Trader account has been reactivated',
      CN: '[Frac] 您的Trader账户已被重新激活',
      JP: 'Frac】アカウント凍結解除のお知らせ',
      VN: '[Frac] Tài khoản Trader của bạn đã được kích hoạt lại',
    },
    WHITELIST_ANNOUNCEMENT: {
      en: '[Frac] Congratulations! You have been whitelisted in an IAO event!',
      cn: '[Frac] 恭喜你! 您已被列入IAO活动的白名单!',
      ja: '【Frac】ホワイトリストに登録されました',
      vi: '[Frac] Xin chúc mừng! Bạn đã được đưa vào whitelist trong một sự kiện IAO!',
    },
    PARTICIPATION_TIME_START: {
      en: '[Frac] Your IAO event has started',
      cn: '[Frac] 您的IAO活动已经开始了',
      ja: '【Frac】IAOイベントが開始されました',
      vi: '[Frac] Sự kiện IAO của bạn đã bắt đầu',
    },
    IAO_EVENT_FAILED: {
      en: '[Frac] The IAO event that you have participated in has failed',
      cn: '[Frac]您所参与的IAO活动没有达标。',
      ja: '【Frac】IAOイベントは成功しませんでした',
      vi: '[Frac] Sự kiện IAO mà bạn tham gia đã thất bại',
    },
    REJECT_IAO_REVENUE_TO_WHITELIST: {
      en: '[Frac] The result of the IAO event that you have participated in has been rejected',
      cn: '[Frac]您所参与的IAO活动的结果被拒绝。',
      ja: '【Frac】IAOイベントはキャンセルされました',
      vi: '[Frac] Kết quả của sự kiện IAO mà bạn tham gia đã bị từ chối',
    },
    IAO_VAULT_SUCCESS: {
      en: '[Frac] The IAO event that you have participated in has completed!',
      cn: '[Frac]您所参与的IAO活动已经完成!',
      ja: '【Frac】 IAOイベントが終了しました',
      vi: '[Frac] Sự kiện IAO mà bạn tham gia đã hoàn thành!',
    },
    IAO_NON_VAULT_SUCCESS: {
      en: '[Frac] The IAO event that you have participated in has completed!',
      cn: '[Frac]您所参与的IAO活动已经完成!',
      ja: '【Frac】IAOイベントが終了しました',
      vi: '[Frac] Sự kiện IAO mà bạn tham gia đã hoàn thành!',
    },
    WHITELIST_EMPTY: 'Empty whitelist!',
    ANNOUNCEMENT: 'New Announcement!',
    IAO_EVENT_VAULT_COMPLETED: '[Frac] Vault IAO event has completed',
    IAO_EVENT_VAULT_FAILED: '[Frac] Vault IAO event has failed',
    IAO_EVENT_NON_VAULT_COMPLETED: '[Frac] Non-vault IAO event has completed',
    FNFT_MERGED: '[Frac] F-NFT has been merged',
    BECAME_MASTER_AFFILIATE: {
      EN: '[Frac] Congratulations! You have been invited to become a Master Affiliate on Frac.io!',
      CN: '[Frac] 恭喜你! 您已被邀请成为Frac.io的主会员!',
      JA: 'Frac】アフィリエイト承認のお知らせ',
      VI: '[Frac] Xin chúc mừng! Bạn đã được mời trở thành Master Affiliate trên Frac.io!',
    },
    REQUEST_NFT_WITHDRAW_COMPLETED: {
      EN: '[Frac] Your withdrawal has succeeded',
      CN: '[Frac]你的撤退已经成功了',
      JA: '【Frac】出金が完了しました',
      VI: '[Frac] Bạn đã rút tiền thành công',
    },
    REDEMPTION_REQUEST_APPROVED: {
      EN: '[Frac] Your redemption request has been approved!',
      CN: '[Frac]您的赎回申请已被批准!',
      JA: '【Frac】資産交換申請が受理されました',
      VI: '[Frac] Yêu cầu mua lại của bạn đã được chấp thuận!',
    },
    REDEMPTION_REQUEST_REJECTED: {
      EN: '[Frac] Your redemption request has been rejected!',
      CN: '[Frac]您的赎回申请被拒绝了!',
      JA: '【Frac】資産交換申請は受理されませんでした',
      VI: '[Frac] Yêu cầu mua lại của bạn đã bị từ chối!',
    },
    DEACTIVATE_FRACTOR: {
      EN: '[Frac] Your Fractor account has been deactivated',
      CN: '[Frac] 您的Fractor账户已被停用',
      JA: '【Frac】アカウント凍結のお知らせ',
      VI: '[Frac] Tài khoản Fractor của bạn đã bị vô hiệu hóa',
    },
    REACTIVATE_FRACTOR: {
      EN: '[Frac] Your Fractor account has been reactivated',
      CN: '[Frac] 您的Fractor账户已被重新激活',
      JA: '【Frac】アカウント凍結解除のお知らせ',
      VI: '[Frac] Tài khoản Fractor của bạn đã được kích hoạt lại',
    },
    WITHDRAWAL_REQUEST_FAILED: {
      EN: '[Frac] Your withdrawal has failed',
      CN: '[Frac]您的提款已经失败',
      JP: '【Frac】出金に失敗しました',
      VN: '',
    },
    WITHDRAWAL_REQUEST_SUCCEEDED: {
      EN: '[Frac] Your withdrawal has succeeded',
      CN: '[Frac]你的撤退已经成功了',
      JP: '【Frac】出金が完了しました',
      VN: '[Frac] Bạn đã rút tiền thành công',
    },
    CANCEL_WITHDRAWAL_REQUEST: {
      EN: '[Frac] Your withdrawal have been rejected',
      CN: '【Frac】您的收益提现申请被拒绝了',
      JP: '[Frac] 収益引き出し申請が拒否されました',
      VN: '[Frac] Yêu cầu rút của bạn đã bị từ chối',
    },
    SECOND_APPROVED_IAO_REQUEST: {
      EN: '[Frac] Your IAO request has been approved',
      CN: '[Frac]您的IAO申请已被批准',
      JP: '【Frac】IAO申請が承認されました',
      VN: '[Frac] Yêu cầu IAO của bạn đã được phê duyệt',
    },
    REJECT_IAO_REQUEST: {
      EN: '[Frac] Your IAO request has been rejected',
      CN: '[Frac]您的IAO申请已被批准',
      JP: '【Frac】IAO申請は承認されませんでした',
      VN: '[Frac] Yêu cầu IAO của bạn đã bị từ chối',
    },
    CREATE_IAO_EVENT_PUBLIC: {
      EN: '[Frac] Your IAO event has been published',
      CN: '[Frac]您的IAO事件已被发布',
      JP: '【Frac】IAOイベントが掲載されました',
      VN: '[Frac] Sự kiện IAO của bạn đã được công bố',
    },
    NON_VAULT_IAO_HAS_COMPLETED: {
      EN: '[Frac] Your non-vault IAO event has completed!',
      CN: '[Frac]您的非拱顶IAO事件已经完成!',
      JP: '【Frac】IAOが終了しました',
      VN: '[Frac] Sự kiện IAO non-vault của bạn đã hoàn tất',
    },
    VAULT_IAO_HAS_COMPLETED: {
      EN: '[Frac] Your vault IAO event has completed!',
      CN: '[Frac] 您的金库IAO活动已经完成!',
      JP: '【Frac】Vault IAOが終了しました',
      VN: '[Frac] Sự kiện IAO vault của bạn đã hoàn tất',
    },
    VAULT_IAO_HAS_FAILED: {
      EN: '[Frac] Your IAO event has failed',
      CN: '[Frac] 你的IAO事件失败了',
      JP: '【Frac】Vault IAOは成功しませんでした',
      VN: '[Frac] Sự kiện IAO của bạn không thành công',
    },
    APPROVED_IAO_REVENUE: {
      EN: '[Frac] Your IAO event’s results have been approved',
      CN: '[Frac]您的IAO活动的结果已被批准',
      JP: '【Frac】IAOの結果が承認されました ',
      VN: '[Frac] Kết quả sự kiện IAO của bạn đã được phê duyệt',
    },
    REJECT_IAO_REVENUE: {
      EN: '[Frac] Your IAO event’s results have been rejected',
      CN: '[Frac] 你的IAO事件的结果被拒绝了',
      JP: '【Frac】IAOの結果は承認されませんでした',
      VN: '[Frac] Kết quả sự kiện IAO của bạn đã bị từ chối',
    },
    GAS_WALLET: '[Frac] Low gas!',
    SUBSCRIBER: {
      EN: '[Frac] Thank you for subscribing to our newsletter',
      CN: '[Frac]感谢您订阅我们的简报',
      JA: '[Frac] ニュースレターへのご登録ありがとうございます',
      VI: '[Frac] Cảm ơn bạn đã đăng ký nhận bản tin của Frac',
    },
    NEW_SUBSCRIPTION: '[Frac] New Newsletter Subscription',
    NEW_UNSUBSCRIPTION: '[Frac] Newsletter Unsubscription',
  },
  TEMPLATE: {
    WITHDRAWAL_REQUEST: {
      EN: 'withdrawal-request-result_en',
      CN: 'withdrawal-request-result_cn',
      JP: 'withdrawal-request-result_jp',
      VN: 'withdrawal-request-result_vn',
    },
    AFFILIATE_WITHDRAWAL_REQUEST: {
      EN: 'affiliate-withdrawal-request-result_en',
      CN: 'affiliate-withdrawal-request-result_cn',
      JP: 'affiliate-withdrawal-request-result_jp',
      VN: 'affiliate-withdrawal-request-result_vn',
    },
    CANCEL_WITHDRAWAL_REQUEST: {
      EN: 'cancel_request_en',
      CN: 'cancel_request_cn',
      JP: 'cancel_request_jp',
      VN: 'cancel_request_vn',
    },
  },
};
