name: admin-be
on:
  pull_request:
    branches: 
      - develop
    types: [closed]
jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.pull_request.merged }}
    runs-on: self-hosted
    steps:
      - name: deploy
        run: | # run with multiple script
          cd /home/debian/source/Admin_BE
          git pull origin develop
          npm install
          npm run build
          pm2 restart iao-admin-be