name: admin-be
on:
  pull_request:
    branches: 
      - staging
    types: [closed]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STG_HOST }} #hostname of server
          username: ${{ secrets.STG_USERNAME }} #username login to server
          key: ${{ secrets.STG_KEY }} #password login to server
          port: ${{ secrets.STG_PORT }} #port of server - often port is 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/source/Admin_BE
            git pull
            npm install
            npm run build
            pm2 restart iao-admin-be
